# Elom Worlanyo, ID: 419493 - Operating Systems Project 3
# Tutor: Professor Lawrence Miller 

all: vmsim vmgenU vmgenWS

vmsim: vmsim.cpp utility.cpp vmsim.h utility.cpp
	g++ -std=c++11 -Wall vmsim.cpp utility.cpp -o vmsim

vmgenU: vmgenU.cpp vmgenU.h
	g++ -std=c++11 -Wall vmgenU.cpp -o vmgenU

vmgenWS: vmgenWS.cpp vmgenWS.h
	g++ -std=c++11 -Wall vmgenWS.cpp -o vmgenWS
