# Elom Worlanyo, ID: 419493 - Operating Systems Project 3
# Tutor: Professor Lawrence Miller 

all: vmsim vmgenU vmgenWS

vmsim: vmsim.cpp utility.cpp vmsim.h utility.cpp
	g++ vmsim.cpp utility.cpp -o vmsim

vmgenU: vmgenU.cpp vmgenU.h
	g++ vmgenU.cpp -o vmgenU

vmgenWS: vmgenWS.cpp vmgenWS.h
	g++ vmgenWS.cpp -o vmgenWS
