# Elom Worlanyo, ID: 419493 - Operating Systems Project 1
# Tutor: Professor Lawrence Miller

philosophers: philosophers.cpp utility.cpp philosophers.h utility.h
	g++ -Wall philosophers.cpp utility.cpp -o philosophers -lpthread

